package backward;
import com.ftn.sbnz.model.models.Team;
import com.ftn.sbnz.model.models.Player;
import com.ftn.sbnz.model.models.TeamType;
import com.ftn.sbnz.model.models.Condition;

rule "Demo"
salience 100
lock-on-active true
when

then
    System.out.println("Defensive Style: nsive Style: nsive Style: nsive Style: nsive Style: Drop Back");
end

rule "A - Our team average rating 3 less than opponent team"
salience 100
lock-on-active true
when
    $yourTeam : Team(teamType == TeamType.YOUR_TEAM)
    $opponentTeam : Team(teamType == TeamType.OPPONENT_TEAM)

    $yourAverageRating : Double() from accumulate(
        Player($pace : pace, $shooting : shooting, $dribbling : dribbling, $passing : passing, $defending : defending, $physical : physical) from $yourTeam.getPlayers(),
        average(($pace + $shooting + $dribbling + $passing + $defending + $physical) / 6.0)
    )

    $opponentAverageRating : Double() from accumulate(
        Player($pace : pace, $shooting : shooting, $dribbling : dribbling, $passing : passing, $defending : defending, $physical : physical) from $opponentTeam.getPlayers(),
        average(($pace + $shooting + $dribbling + $passing + $defending + $physical) / 6.0)
    )

    eval($yourAverageRating < $opponentAverageRating - 3)
then
    System.out.println("Defensive Style: Drop Back");
    System.out.println("Width: 30");
    System.out.println("Depth: 25");
    System.out.println("Build Up Play: Long Ball");
    System.out.println("Chance Creation: Forward Runs");
    System.out.println("Width: 40");
    System.out.println("Players Run into Box: Low");
end

rule "B - Average ratings difference is within 3"
salience 90
lock-on-active true
when
    $yourTeam : Team(teamType == TeamType.YOUR_TEAM)
    $opponentTeam : Team(teamType == TeamType.OPPONENT_TEAM)

    $yourAverageRating : Double() from accumulate(
        Player($pace : pace, $shooting : shooting, $dribbling : dribbling, $passing : passing, $defending : defending, $physical : physical) from $yourTeam.getPlayers(),
        average(($pace + $shooting + $dribbling + $passing + $defending + $physical) / 6.0)
    )

    $opponentAverageRating : Double() from accumulate(
        Player($pace : pace, $shooting : shooting, $dribbling : dribbling, $passing : passing, $defending : defending, $physical : physical) from $opponentTeam.getPlayers(),
        average(($pace + $shooting + $dribbling + $passing + $defending + $physical) / 6.0)
    )

    eval(Math.abs($yourAverageRating - $opponentAverageRating) <= 3)
then
    insertLogical(new Condition("B"));
end

rule "C - Our team average rating 3 greater than opponent team"
salience 80
lock-on-active true
when
    $yourTeam : Team(teamType == TeamType.YOUR_TEAM)
    $opponentTeam : Team(teamType == TeamType.OPPONENT_TEAM)

    $yourAverageRating : Double() from accumulate(
        Player($pace : pace, $shooting : shooting, $dribbling : dribbling, $passing : passing, $defending : defending, $physical : physical) from $yourTeam.getPlayers(),
        average(($pace + $shooting + $dribbling + $passing + $defending + $physical) / 6.0)
    )

    $opponentAverageRating : Double() from accumulate(
        Player($pace : pace, $shooting : shooting, $dribbling : dribbling, $passing : passing, $defending : defending, $physical : physical) from $opponentTeam.getPlayers(),
        average(($pace + $shooting + $dribbling + $passing + $defending + $physical) / 6.0)
    )

    eval($yourAverageRating > $opponentAverageRating + 3)
then
    insertLogical(new Condition("C"));
end

rule "D - Opponent team worst attributes are passing and dribbling"
salience 70
lock-on-active true
when
    $opponentTeam : Team(teamType == TeamType.OPPONENT_TEAM)

    $averagePassing : Double() from accumulate(
        Player($passing : passing) from $opponentTeam.getPlayers(),
        average($passing)
    )

    $averageDribbling : Double() from accumulate(
        Player($dribbling : dribbling) from $opponentTeam.getPlayers(),
        average($dribbling)
    )

    $averagePace : Double() from accumulate(
        Player($pace : pace) from $opponentTeam.getPlayers(),
        average($pace)
    )

    $averageShooting : Double() from accumulate(
        Player($shooting : shooting) from $opponentTeam.getPlayers(),
        average($shooting)
    )

    $averageDefending : Double() from accumulate(
        Player($defending : defending) from $opponentTeam.getPlayers(),
        average($defending)
    )

    $averagePhysical : Double() from accumulate(
        Player($physical : physical) from $opponentTeam.getPlayers(),
        average($physical)
    )

    eval($averagePassing <= $averagePace && $averagePassing <= $averageShooting && $averagePassing <= $averageDefending && $averagePassing <= $averagePhysical)
    eval($averageDribbling <= $averagePace && $averageDribbling <= $averageShooting && $averageDribbling <= $averageDefending && $averageDribbling <= $averagePhysical)
then
    insertLogical(new Condition("D"));
end

rule "E - Opponent team worst attribute is physical"
salience 60
lock-on-active true
when
    $opponentTeam : Team(teamType == TeamType.OPPONENT_TEAM)

    $averagePhysical : Double() from accumulate(
        Player($physical : physical) from $opponentTeam.getPlayers(),
        average($physical)
    )

    $averagePace : Double() from accumulate(
        Player($pace : pace) from $opponentTeam.getPlayers(),
        average($pace)
    )

    $averageShooting : Double() from accumulate(
        Player($shooting : shooting) from $opponentTeam.getPlayers(),
        average($shooting)
    )

    $averageDribbling : Double() from accumulate(
        Player($dribbling : dribbling) from $opponentTeam.getPlayers(),
        average($dribbling)
    )

    $averagePassing : Double() from accumulate(
        Player($passing : passing) from $opponentTeam.getPlayers(),
        average($passing)
    )

    $averageDefending : Double() from accumulate(
        Player($defending : defending) from $opponentTeam.getPlayers(),
        average($defending)
    )

    eval($averagePhysical <= $averagePace && $averagePhysical <= $averageShooting && $averagePhysical <= $averageDribbling && $averagePhysical <= $averagePassing && $averagePhysical <= $averageDefending)
then
    insertLogical(new Condition("E"));
end

rule "H - Opponent team worst attribute is pace"
salience 50
lock-on-active true
when
    $opponentTeam : Team(teamType == TeamType.OPPONENT_TEAM)

    $averagePace : Double() from accumulate(
        Player($pace : pace) from $opponentTeam.getPlayers(),
        average($pace)
    )

    $averageShooting : Double() from accumulate(
        Player($shooting : shooting) from $opponentTeam.getPlayers(),
        average($shooting)
    )

    $averageDribbling : Double() from accumulate(
        Player($dribbling : dribbling) from $opponentTeam.getPlayers(),
        average($dribbling)
    )

    $averagePassing : Double() from accumulate(
        Player($passing : passing) from $opponentTeam.getPlayers(),
        average($passing)
    )

    $averageDefending : Double() from accumulate(
        Player($defending : defending) from $opponentTeam.getPlayers(),
        average($defending)
    )

    $averagePhysical : Double() from accumulate(
        Player($physical : physical) from $opponentTeam.getPlayers(),
        average($physical)
    )

    eval($averagePace <= $averageShooting && $averagePace <= $averageDribbling && $averagePace <= $averagePassing && $averagePace <= $averageDefending && $averagePace <= $averagePhysical)
then
    insertLogical(new Condition("H"));
end

rule "J - None of D, E, H are true"
salience 40
lock-on-active true
when
    not (Condition(type == "D") or Condition(type == "E") or Condition(type == "H"))
then
    insertLogical(new Condition("J"));
end

rule "K - Our team's average physical is greater than other attributes by 3"
salience 30
lock-on-active true
when
    $yourTeam : Team(teamType == TeamType.YOUR_TEAM)

    $averagePhysical : Double() from accumulate(
        Player($physical : physical) from $yourTeam.getPlayers(),
        average($physical)
    )

    $averagePace : Double() from accumulate(
        Player($pace : pace) from $yourTeam.getPlayers(),
        average($pace)
    )

    $averageShooting : Double() from accumulate(
        Player($shooting : shooting) from $yourTeam.getPlayers(),
        average($shooting)
    )

    $averageDribbling : Double() from accumulate(
        Player($dribbling : dribbling) from $yourTeam.getPlayers(),
        average($dribbling)
    )

    $averagePassing : Double() from accumulate(
        Player($passing : passing) from $yourTeam.getPlayers(),
        average($passing)
    )

    $averageDefending : Double() from accumulate(
        Player($defending : defending) from $yourTeam.getPlayers(),
        average($defending)
    )

    eval($averagePhysical > $averagePace + 3 && $averagePhysical > $averageShooting + 3 && $averagePhysical > $averageDribbling + 3 && $averagePhysical > $averagePassing + 3 && $averagePhysical > $averageDefending + 3)
then
    insertLogical(new Condition("K"));
end

rule "M - Our team's average passing is greater than other attributes by 3"
salience 20
lock-on-active true
when
    $yourTeam : Team(teamType == TeamType.YOUR_TEAM)

    $averagePassing : Double() from accumulate(
        Player($passing : passing) from $yourTeam.getPlayers(),
        average($passing)
    )

    $averagePace : Double() from accumulate(
        Player($pace : pace) from $yourTeam.getPlayers(),
        average($pace)
    )

    $averageShooting : Double() from accumulate(
        Player($shooting : shooting) from $yourTeam.getPlayers(),
        average($shooting)
    )

    $averageDribbling : Double() from accumulate(
        Player($dribbling : dribbling) from $yourTeam.getPlayers(),
        average($dribbling)
    )

    $averageDefending : Double() from accumulate(
        Player($defending : defending) from $yourTeam.getPlayers(),
        average($defending)
    )

    $averagePhysical : Double() from accumulate(
        Player($physical : physical) from $yourTeam.getPlayers(),
        average($physical)
    )

    eval($averagePassing > $averagePace + 3 && $averagePassing > $averageShooting + 3 && $averagePassing > $averageDribbling + 3 && $averagePassing > $averageDefending + 3 && $averagePassing > $averagePhysical + 3)
then
    insertLogical(new Condition("M"));
end

rule "O - Our team's average pace is greater than other attributes by 3"
salience 10
lock-on-active true
when
    $yourTeam : Team(teamType == TeamType.YOUR_TEAM)

    $averagePace : Double() from accumulate(
        Player($pace : pace) from $yourTeam.getPlayers(),
        average($pace)
    )

    $averageShooting : Double() from accumulate(
        Player($shooting : shooting) from $yourTeam.getPlayers(),
        average($shooting)
    )

    $averageDribbling : Double() from accumulate(
        Player($dribbling : dribbling) from $yourTeam.getPlayers(),
        average($dribbling)
    )

    $averagePassing : Double() from accumulate(
        Player($passing : passing) from $yourTeam.getPlayers(),
        average($passing)
    )

    $averageDefending : Double() from accumulate(
        Player($defending : defending) from $yourTeam.getPlayers(),
        average($defending)
    )

    $averagePhysical : Double() from accumulate(
        Player($physical : physical) from $yourTeam.getPlayers(),
        average($physical)
    )

    eval($averagePace > $averageShooting + 3 && $averagePace > $averageDribbling + 3 && $averagePace > $averagePassing + 3 && $averagePace > $averageDefending + 3 && $averagePace > $averagePhysical + 3)
then
    insertLogical(new Condition("O"));
end

rule "P - None of K, M, O are true"
salience 0
lock-on-active true
when
    not (Condition(type == "K") or Condition(type == "M") or Condition(type == "O"))
then
    insertLogical(new Condition("P"));
end

rule "Strategy 1 - A"
salience -10
lock-on-active true
when
    $conditionA : Condition(type == "A")
then
    System.out.println("Defensive Style: Drop Back");
    System.out.println("Width: 30");
    System.out.println("Depth: 25");
    System.out.println("Build Up Play: Long Ball");
    System.out.println("Chance Creation: Forward Runs");
    System.out.println("Width: 40");
    System.out.println("Players Run into Box: Low");
end

rule "Strategy 2 - B and D"
salience -20
lock-on-active true
when
    $conditionB : Condition(type == "B")
    $conditionD : Condition(type == "D")
then
    System.out.println("Defensive Style: Pressure on Heavy Touch");
    System.out.println("Width: 50");
    System.out.println("Depth: 50");
    System.out.println("Build Up Play: Fast Build Up");
    System.out.println("Chance Creation: Direct Passing");
    System.out.println("Width: 60");
    System.out.println("Players Run into Box: Medium");
end

rule "Strategy 3 - B and E"
salience -30
lock-on-active true
when
    $conditionB : Condition(type == "B")
    $conditionE : Condition(type == "E")
then
    System.out.println("Defensive Style: Constant Pressure");
    System.out.println("Width: 60");
    System.out.println("Depth: 70");
    System.out.println("Build Up Play: Fast Build Up");
    System.out.println("Chance Creation: Direct Passing");
    System.out.println("Width: 60");
    System.out.println("Players Run into Box: Medium");
end

rule "Strategy 4 - B and H"
salience -40
lock-on-active true
when
    $conditionB : Condition(type == "B")
    $conditionH : Condition(type == "H")
then
    System.out.println("Defensive Style: Drop Back");
    System.out.println("Width: 50");
    System.out.println("Depth: 30");
    System.out.println("Build Up Play: Long Ball");
    System.out.println("Chance Creation: Forward Runs");
    System.out.println("Width: 65");
    System.out.println("Players Run into Box: High");
end

rule "Strategy 5 - J and K or C and K"
salience -50
lock-on-active true
when
    $conditionJ : Condition(type == "J")
    $conditionK : Condition(type == "K")
    or
    $conditionC : Condition(type == "C")
    $conditionK : Condition(type == "K")
then
    System.out.println("Defensive Style: Constant Pressure");
    System.out.println("Width: 50");
    System.out.println("Depth: 70");
    System.out.println("Build Up Play: Fast Build Up");
    System.out.println("Chance Creation: Direct Passing");
    System.out.println("Width: 40");
    System.out.println("Players Run into Box: Very High");
end

rule "Strategy 6 - J and M or C and M"
salience -60
lock-on-active true
when
    $conditionJ : Condition(type == "J")
    $conditionM : Condition(type == "M")
    or
    $conditionC : Condition(type == "C")
    $conditionM : Condition(type == "M")
then
    System.out.println("Defensive Style: Press After Possession Loss");
    System.out.println("Width: 70");
    System.out.println("Depth: 60");
    System.out.println("Build Up Play: Slow Build Up");
    System.out.println("Chance Creation: Possession");
    System.out.println("Width: 70");
    System.out.println("Players Run into Box: Very High");
end

rule "Strategy 7 - J and O or C and O"
salience -70
lock-on-active true
when
    $conditionJ : Condition(type == "J")
    $conditionO : Condition(type == "O")
    or
    $conditionC : Condition(type == "C")
    $conditionO : Condition(type == "O")
then
    System.out.println("Defensive Style: Drop Back");
    System.out.println("Width: 60");
    System.out.println("Depth: 30");
    System.out.println("Build Up Play: Fast Build Up");
    System.out.println("Chance Creation: Forward Runs");
    System.out.println("Width: 70");
    System.out.println("Players Run into Box: Medium");
end

rule "Strategy 8 - J and P or C and P"
salience -80
lock-on-active true
when
    $conditionJ : Condition(type == "J")
    $conditionP : Condition(type == "P")
    or
    $conditionC : Condition(type == "C")
    $conditionP : Condition(type == "P")
then
    System.out.println("Defensive Style: Balanced");
    System.out.println("Width: 50");
    System.out.println("Depth: 50");
    System.out.println("Build Up Play: Balanced");
    System.out.println("Chance Creation: Balanced");
    System.out.println("Width: 50");
    System.out.println("Players Run into Box: High");
end
